# Workflow Code: PanickyGnat_v5    DO NOT REMOVE
# Purpose:
#    Cleans up GH Releases that are created for a branch. The same functionality
#    is included in the .NET CI Build workflow when a PR is merged but is also
#    included in this separate workflow in case in needs to be run manually.
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    - Azure App Service or Function (Optional Template)
#    - On-Prem Service               (Optional Template)
#    - On-Prem Site                  (Optional Template)

name: Cleanup Releases for Branches
run-name: Cleanup Releases for ${{ inputs.branch-name }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: The name of the branch the cleanup should be run for
        required: true
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up the releases that were created for the branch
        uses: im-open/delete-prereleases-for-branch@v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          branch-name: ${{ github.event.inputs.branch-name }}
