# Workflow Code: TrustingCockroach_v44    DO NOT REMOVE
# Purpose:
#    Automatically builds the project and runs tests with code coverage. If
#    everything is green, a new semantic version is calculated and a new package
#    version and tag are pushed to the repository. When the PR is merged, the
#    package versions created for each branch commit in the PR are removed.
#
# Frequency: This workflow should be duplicated once per nuget package in the repository
#
# Projects to use this Template with:
#    - Nuget Package (Core Template)
#
# TODO Prerequisites:
#    - If the project contains a local nuget.config remove it.  It interferes with restoring packages on the GitHub Action runners.
#    - Make sure the .csproj file has been updated with the appropriate values required for GH Packages (PackageId, Version, RepositoryUrl)
#      https://github.com/im-practices/git-er-done/blob/main/packages/publish-nuget.md
#    - This workflow uses the elevated GH_PACKAGES_TOKEN secret to read/write/delete packages.  It is at the organization level but only
#      available to select repos.  To use this let a member of the SWAT team or Infra-Purple know and it can be enabled for your repository.

name: 'Build and Publish Nuget package'

on:
  # This workflow will run for the PR events:
  #   opened/reopened: A PR is opened/re-opened,
  #   synchronize: The PR's head branch is updated (commits pushed, the base branch changed or the head is updated from the base branch)
  #   closed: A PR is merged or closed (The setup-build-workflow job makes sure we only run if a merge happened, not when a close happens)
  pull_request:
    # TODO: This will create a new nuget package for each push to the PR, determine if that is the desired behavior or if you only
    #        want a package created when a merge to main happens.
    types: [opened, reopened, synchronize, closed]

    # TODO: If there are multiple projects in the repo, add the path to the nuget package project so changes to those projects don't trigger this workflow
    #        If the repo only contains the nuget package project, delete the paths:
    paths:
      - ''

env:
  READ_PKG_TOKEN: ${{ secrets.READ_PKG_TOKEN }} # This is an org-level secret # TODO: this env can be removed if the project does not contain an .npmrc/nuget.config file that needs this value
  TIMEZONE: 'america/denver' # TODO: Verify timezone

jobs:
  # This job utilizes a reusable workflow which will:
  #   1 - Examine the triggers and set various flags for subsequent jobs to use when evaluating whether to run
  #   2 - Print a workflow summary
  #   3 - Generate the next version for the repo
  setup-build-workflow:
    uses: im-practices/.github/.github/workflows/im-reusable-setup-build-workflow.yml@v2
    with:
      tag-prefix: 'none'
      # default-branch: main # TODO:  Update and include this argument if default branch is different
      # workflow-summary : | # TODO:  If desired, the workflow summary that is generated can be overridden by providing this custom value.

  build-test-publish:
    runs-on: im-linux
    needs: [setup-build-workflow]
    if: needs.setup-build-workflow.outputs.CONTINUE_WORKFLOW == 'true'

    defaults:
      run:
        shell: bash

    env:
      NEXT_VERSION: ${{ needs.setup-build-workflow.outputs.NEXT_VERSION }}
      NEXT_VERSION_NO_PREFIX: ${{ needs.setup-build-workflow.outputs.NEXT_VERSION_NO_PREFIX }}
      IS_MERGE_TO_MAIN: ${{ needs.setup-build-workflow.outputs.IS_MERGE_TO_MAIN }}
      IS_DEPENDABOT_PR: ${{ needs.setup-build-workflow.outputs.IS_DEPENDABOT_PR }}
      PRERELEASE: ${{ needs.setup-build-workflow.outputs.IS_PRERELEASE }}
      CODE_COVERAGE_CHECK_NAME_DOTNET: 'dotnet code coverage'
      CODE_COVERAGE_DIR_DOTNET: 'coverage-results/dotnet'
      CODE_COVERAGE_REPORT_NAME_DOTNET: '<project-name> .Net Code Coverage' # TODO: Replace <project-name>
      DOTNET_VERSION: '' # TODO: Add the .net version
      NUGET_PROJ_DIR: '' # TODO: Add the directory containing the nuget package project like, ./src/MyNugetProj
      NUGET_PROJ_NAME: '' # TODO: Add the name of the csproj for the nuget package
      NUGET_TEST_PROJECT: '' # TODO: Add the filename including path of the test project for your nuget package like ./tests/nugetTest/nugetTest.csproj
      PKG_NAME: '' # TODO: If dual publishing to artifactory, add the name of the nuget package in Artifactory, otherwise delete
      # CSPROJ_NAME: '' # TODO: For older projects that must be built with nuget pack (instead of dotnet pack) add the name of your csproj file, otherwise delete

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # TODO: If you are using any nuget/npm packages from GitHub Packages uncomment this step
      # - name: Authenticate with GitHub Packages
      #   uses: im-open/authenticate-with-gh-package-registries@v1.1
      #   with:
      #     read-pkg-token: ${{ secrets.READ_PKG_TOKEN }}  # This is an org-level secret
      #     orgs: 'im-enrollment,im-practices' # TODO: Verify list of orgs packages will be pulled from

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: './.dotnet'

      - name: dotnet build and pack nuget project
        # dotnet pack also builds by default, so just go ahead and create the package.
        # Set "PackageOutputPath" to place the resulting .nupkg file where the "Push to GH Packages" step can find it later.
        # Set "Version" which, by default, becomes both the assembly and Package version.
        # TODO: There are other methods for setting the version besides specifying it here.  You can update the value in the .csproj before building
        #        and remove the -p:Version property below, or the version could be passed in from a workflow_dispatch input if desired.
        # Set "RepositoryUrl" so the resulting nupkg is ready to be uploaded to GitHub packages and so the repo name and location doesn't need to be hard-coded in the .csproj.
        run: dotnet pack ${{ env.NUGET_PROJ_DIR }}/${{ env.NUGET_PROJ_NAME }} --configuration Release -p:PackageOutputPath=${{ env.NUGET_PROJ_DIR }} -p:Version=${{ env.NEXT_VERSION_NO_PREFIX }} -p:RepositoryUrl=${{ github.repositoryUrl }}

      # TODO: If this is an older project you may need to use the nuget command directly and add options as applicable.
      # - name: Nuget Pack
      #   working-directory: ${{ env.NUGET_PROJ_DIR }}
      #   run: nuget pack ${{ env.CSPROJ_NAME }} -Build -Properties Configuration=Release;version="${{ env.NEXT_VERSION_NO_PREFIX }}"

      - name: dotnet build test project
        run: dotnet build ${{ env.NUGET_TEST_PROJECT }} --configuration Release

      # TODO: The test projects need a package reference to coverlet.msbuild for this to output the coverage reports correctly:
      # <PackageReference Include="coverlet.msbuild" Version="3.1.0" />
      # TODO: Filters can be added to exclude certain tests: https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=xunit
      - name: dotnet test with coverage
        continue-on-error: true
        run: dotnet test ${{ env.NUGET_TEST_PROJECT }} --logger trx --no-build --configuration Release /property:CollectCoverage=True /property:CoverletOutputFormat=opencover

      - name: create status check/comment for test results
        id: dotnet_test_check
        uses: im-open/process-dotnet-test-results@v3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          timezone: ${{ env.TIMEZONE }}
          # TODO: Determine if you would like status checks, pr comments or both
          create-status-check: true
          create-pr-comment: true
          # update-comment-if-one-exists: false # TODO: By default this creates one comment and updates it for each run.  Uncomment if you wish to have one new comment for every workflow run.

      - name: create code coverage report
        if: env.IS_DEPENDABOT_PR == 'false'
        uses: im-open/code-coverage-report-generator@v5.0
        with:
          reports: '*/**/coverage.opencover.xml'
          targetdir: ${{ env.CODE_COVERAGE_DIR_DOTNET }}
          title: ${{ env.CODE_COVERAGE_REPORT_NAME_DOTNET }}
          tag: 'Workflow: ${{ github.workflow }} <br/> Run Number: ${{ github.run_number }} <br/> Run ID: ${{ github.run_id }}'
          # TODO: Add the appropriate filters to each type.
          # The filters are a ; separated list of items to include(+) or exclude(-).  Wildcards are accepted.
          # For instance: -xunit*;-Dapper;-*.Tests
          assemblyfilters: ''
          filefilters: ''
          classfilters: ''

      - name: create status check/comment for code coverage results
        if: env.IS_DEPENDABOT_PR == 'false'
        id: dotnet_coverage_check
        uses: im-open/process-code-coverage-summary@v2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          summary-file: '${{ env.CODE_COVERAGE_DIR_DOTNET }}/Summary.md'
          report-name: ${{ env.CODE_COVERAGE_REPORT_NAME_DOTNET }}
          check-name: ${{ env.CODE_COVERAGE_CHECK_NAME_DOTNET }}
          # TODO: Determine if you would like status checks, pr comments or both
          create-status-check: true
          create-pr-comment: true
          # update-comment-if-one-exists: false # TODO: By default this creates one comment and updates it for each run.  Uncomment if you wish to have one new comment for every workflow run.
          # TODO: Set the thresholds for branch and line coverage.
          # When set to 0 the outcome is neutral.  Otherwise line/branch coverage will be a 'failure' if actual coverage < threshold.
          line-threshold: 0
          branch-threshold: 0

      - name: zip and upload dotnet code coverage report
        if: always() && steps.dotnet_coverage_check.outcome == 'success' && env.IS_DEPENDABOT_PR == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CODE_COVERAGE_REPORT_NAME_DOTNET }}
          path: ${{ env.CODE_COVERAGE_DIR_DOTNET }}
          retention-days: 15 # Cannot exceed 30 days.

      - name: Check for Test Failures
        if: steps.dotnet_test_check.outputs.test-outcome != 'Passed' || (steps.dotnet_coverage_check.outputs.coverage-outcome != 'Passed' && steps.dotnet_coverage_check.outputs.coverage-outcome != 'Skipped')
        run: |
          echo "There were test or code coverage failures.  A release will not be created."
          exit 1

      # If this version already exists in GitHub Packages, this step will fail.
      - name: Push to GH Packages
        working-directory: ${{ env.NUGET_PROJ_DIR }}
        run: |
          # Searches for all nuget packages
          nupkg=$(find . -type f -name "*.nupkg")

          # GITHUB_TOKEN is a special per-job token generated by GH for interacting with the repo
          dotnet nuget push "$nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Create a tag for main builds
        uses: actions/github-script@v7
        if: ${{ env.IS_MERGE_TO_MAIN }} == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ env.NEXT_VERSION }}`,
              sha: context.sha
            });

      - name: Cleanup pre-release package versions
        if: env.IS_MERGE_TO_MAIN == 'true'
        uses: im-open/delete-branch-package-versions@v3.1
        with:
          github-token: ${{ secrets.GH_PACKAGES_TOKEN }} # This is a special org-level secret that needs to be authorized for this repo
          organization: ${{ github.repository_owner }}
          branch-name: ${{ github.head_ref }}
          package-type: 'nuget'
          package-names: '' # TODO: Add comma separated list of packages to delete (the base name without any versions, like IdentityCient or Mktp.Logging)

  # This job utilizes a reusable workflow which will:
  #   1 - Send a status to a teams channel
  #   2 - Add a comment to the PR with the status/next version
  #   3 - Check for workflow failures
  finish-build:
    if: always() && needs.setup-build-workflow.outputs.CONTINUE_WORKFLOW == 'true'
    needs: [setup-build-workflow, build-test-publish]
    uses: im-practices/.github/.github/workflows/im-reusable-finish-build-workflow.yml@v2
    with:
      next-version: ${{ needs.setup-build-workflow.outputs.NEXT_VERSION }}
      title-of-teams-post: 'Build and Publish <project-name> to GH Packages' # TODO: Replace <project-name>
      is-merge-to-main: ${{ needs.setup-build-workflow.outputs.IS_MERGE_TO_MAIN }}
      ms-teams-uri: ${{ vars.MS_TEAMS_URI }}
      # timezone: 'america/denver'         # TODO: Include this argument and update if your timezone is not america/denver
      # additional-pr-comment-content: |   # TODO: Additional PR content can be added if desired.  Links for the workflow run and text for the next version/tag are included by default
      # custom-facts-for-team-channel: |   # TODO: These are the custom facts that will be included the different Teams posts by default.  If adjusting the facts that are supplied, they must be a valid JSON array.
      #   [
      #     { "name": "Workflow", "value": "${{ github.workflow }}" },
      #     { "name": "Run", "value": "${{ github.run_id }}" },
      #     { "name": "Actor", "value": "${{ github.actor }}" },
      #     { "name": "Version", "value": "${{ needs.setup-build-workflow.outputs.NEXT_VERSION }}" }
      #   ]
