# Workflow Code: GloomyBadger_v18    DO NOT REMOVE
# Purpose:
#    Automatically calculates the next semantic version, runs an npm ci, an npm run tests
#    if there is one, an npm publish and then pushes a latest tag for main builds. When the
#    PR is merged, the package versions created for each branch commit in the PR are removed.
#
# Frequency: This workflow should be duplicated once per npm package in the repository
#
# Projects to use this Template with:
#    - npm Package (Core Template)
#
# TODO: Prerequisites:
#    - Update the package.json file required values for GH Packages (name, version, repository, publishConfig.registry)
#      https://github.com/im-practices/git-er-done/blob/main/packages/publish-npm.md
#    - This workflow uses the elevated GH_PACKAGES_TOKEN secret to read/write/delete packages. This is an org-level secret but is
#      only available to select repos.  To use this let a member of SWAT or Infra-Purple know and it can be enabled for your repo.

name: 'Build and Publish npm Package'

on:
  # This workflow will run for the PR events:
  #   opened/reopened: A PR is opened/re-opened,
  #   synchronize: The PR's head branch is updated (commits pushed, the base branch changed or the head is updated from the base branch)
  #   closed: A PR is merged or closed (The examine-triggers job makes sure we only run if a merge happened, not when a close happens)
  pull_request:
    # TODO: This will create a new npm package for each push to the PR, determine if that is the desired behavior or if you only
    #        want a package created when a merge to main happens.
    types: [opened, reopened, synchronize, closed]

    # TODO: If there are multiple projects in the repo, add the path to the npm package project so changes to those projects don't trigger this workflow
    #        If the repo only contains the npm package project, delete the paths:
    paths:
      - ''

env:
  READ_PKG_TOKEN: ${{ secrets.READ_PKG_TOKEN }} # This is an org-level secret # TODO: this env can be removed if the project does not contain an .npmrc file that needs this value
  TIMEZONE: 'america/denver'
  REPO_URL: 'https://github.com/${{ github.repository }}'

jobs:
  examine-triggers:
    runs-on: ubuntu-latest
    outputs:
      CONTINUE_WORKFLOW: ${{ env.CONTINUE_WORKFLOW }}
      IS_MERGE_TO_MAIN: ${{ env.IS_MERGE_TO_MAIN }}
      PRERELEASE: ${{ env.PRERELEASE }}
      DIST_TAG: ${{ env.DIST_TAG }}

    steps:
      - run: |
          echo "CONTINUE_WORKFLOW=true" >> $GITHUB_ENV
          echo "IS_MERGE_TO_MAIN=false" >> $GITHUB_ENV
          echo "PRERELEASE=true" >> $GITHUB_ENV
          echo "DIST_TAG=${{ github.head_ref }}" >> $GITHUB_ENV

      - if: github.event.action == 'closed' && github.event.pull_request.merged == false
        run: echo "CONTINUE_WORKFLOW=false" >> $GITHUB_ENV

      - if: github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' # TODO: verify default branch name
        run: |
          echo "IS_MERGE_TO_MAIN=true" >> $GITHUB_ENV
          echo "PRERELEASE=false" >> $GITHUB_ENV
          echo "DIST_TAG=latest" >> $GITHUB_ENV

  build-and-publish-to-gpr:
    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners
    needs: [examine-triggers]
    if: needs.examine-triggers.outputs.CONTINUE_WORKFLOW == 'true'

    env:
      IS_MERGE_TO_MAIN: ${{ needs.examine-triggers.outputs.IS_MERGE_TO_MAIN }}
      PRERELEASE: ${{ needs.examine-triggers.outputs.PRERELEASE }}
      DIST_TAG: ${{ needs.examine-triggers.outputs.DIST_TAG }}

    defaults:
      run:
        shell: bash
        working-directory: '' # TODO: Add the path to the npm package project

    outputs:
      NEXT_VERSION: ${{ steps.version.outputs.NEXT_VERSION }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 12 # TODO: verify node version
          registry-url: https://npm.pkg.github.com/

      # TODO: If the project contains dependencies to other npm packages in GitHub's npm package registry, uncomment this step, otherwise delete
      # - name: Authenticate with GitHub Packages for Restoring Packages
      #   uses: im-open/authenticate-with-gh-package-registries@v1.0.5
      #   with:
      #     read-pkg-token: ${{ secrets.READ_PKG_TOKEN }} # This is an org-level secret
      #     orgs: 'im-client,im-enrollment,im-practices' # TODO: Verify list of orgs packages will be pulled from

      - name: Calculate next version
        id: version
        uses: im-open/git-version-lite@v2.0.8
        with:
          calculate-prerelease-version: ${{ env.PRERELEASE }}
          branch-name: ${{ github.head_ref }} # This is only populated when the trigger is pull_request, otherwise it is empty
          tag-prefix: 'none' # TODO: verify your prefix, the new ci workflows add v automatically but npm packages typically won't have a prefix

      # TODO: Add any additional flags you need to version your project like --allow-same-version
      - run: npm version ${{ steps.version.outputs.NEXT_VERSION }}

      # TODO: Add any additional flags you need to restore packages in  your project like --ignore-scripts
      # TODO: For some projects you may need several commands, one to do this at the root, one to change directories and one to do it in the package dir
      - run: npm ci

      # TODO: If you have tests that run for the npm package, add a new run step with the appropriate npm command
      # - run: npm run tests

      - name: reset .npmrc for publishing
        run: npm set //npm.pkg.github.com/:_authToken '${{ secrets.GITHUB_TOKEN }}'

      - run: npm publish --tag ${{ env.DIST_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo

      - name: Create a tag for main builds
        uses: actions/github-script@v4
        if: ${{ env.IS_MERGE_TO_MAIN }} == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.version.outputs.NEXT_VERSION }}`,
              sha: context.sha
            });

      - name: Cleanup pre-release package versions
        if: env.IS_MERGE_TO_MAIN == 'true'
        uses: im-open/delete-branch-package-versions@v1.0.4
        with:
          github-token: ${{ secrets.GH_PACKAGES_TOKEN }} # This is a special org-level secret that needs to be authorized for this repo
          organization: '' # TODO: Add the organization this repo is in
          branch-name: ${{ github.head_ref }}
          package-type: 'npm'
          package-name: '' # TODO: Add the name of the package (the base name without any versions, like screen or via-scripts)

  finish-build:
    if: always() && needs.examine-triggers.outputs.CONTINUE_WORKFLOW == 'true'
    needs: [examine-triggers, build-and-publish-to-gpr]
    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners
    env:
      NEXT_VERSION: ${{ needs.build-and-publish-to-gpr.outputs.NEXT_VERSION }}
      IS_MERGE_TO_MAIN: ${{ needs.examine-triggers.outputs.IS_MERGE_TO_MAIN }}

    steps:
      - uses: im-open/workflow-conclusion@v2.0.2
        id: conclusion
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          additional-conclusions: |
            [
              { "name": "sam.yaml validation", "conclusion" : "${{ needs.validate-sam-yaml.outputs.validate }}" }
            ]

      - name: Send Status to Teams
        if: always()
        uses: im-open/post-status-to-teams-action@v1.1.2
        with:
          title: 'Build and Publish <project-name> to GH Packages' # TODO: Replace <project-name>
          workflow-status: ${{ steps.conclusion.outputs.workflow_conclusion }}
          workflow-type: Build
          teams-uri: ${{ secrets.MS_TEAMS_URI }} # This is a repo-level secret
          timezone: ${{ env.TIMEZONE }}
          custom-facts: |
            [
              { "name": "Workflow", "value": "${{ github.workflow }}" },
              { "name": "Run", "value": "${{ github.run_number }}" },
              { "name": "Actor", "value": "${{ github.actor }}" },
              { "name": "Version", "value": "${{ env.NEXT_VERSION }}" }
            ]

      - name: Comment on PR with version ${{ env.NEXT_VERSION }}
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          script: |
            let nextVersion = '${{ env.NEXT_VERSION }}';
            let isMergeToMain = '${{ env.IS_MERGE_TO_MAIN }}' == 'true';

            let tagText = '- Tag - N/A';
            let testPackageText = '';
            if (nextVersion && nextVersion.length > 0) {
              tagText =  isMergeToMain ?
                `- [Tag - ${nextVersion}](${{ env.REPO_URL }}/releases/tag/${nextVersion})` :
                `- Next Version - ${nextVersion}`;
              testPackageText = `- To test this version try running:
              \`\`\`bash
              npm install @<org>/<package-name>@${nextVersion} # TODO: Replace <org>/<package-name> with actual values
              \`\`\`
            `;
            }

            const commentBody = `
            - [Workflow Run - ${{ steps.conclusion.outputs.workflow_conclusion }}](${{ env.REPO_URL }}/actions/runs/${{ github.run_id }})
            ${tagText}
            ${testPackageText}
              `;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      - name: Check for Failures
        if: steps.conclusion.outputs.workflow_conclusion == 'failure'
        run: |
          echo "There were errors in the workflow.  Check the workflow-conclusion step above for more details on what failed."
          exit 1
