# Workflow Code: GloomyBadger_v27    DO NOT REMOVE
# Purpose:
#    Automatically calculates the next semantic version, runs an npm ci, an npm run tests
#    if there is one, an npm publish and then pushes a latest tag for main builds. When the
#    PR is merged, the package versions created for each branch commit in the PR are removed.
#
# Frequency: This workflow should be duplicated once per npm package in the repository
#
# Projects to use this Template with:
#    - npm Package (Core Template)
#
# TODO: Prerequisites:
#    - Update the package.json file required values for GH Packages (name, version, repository, publishConfig.registry)
#      https://github.com/im-practices/git-er-done/blob/main/packages/publish-npm.md
#    - This workflow uses the elevated GH_PACKAGES_TOKEN secret to read/write/delete packages. This is an org-level secret but is
#      only available to select repos.  To use this let a member of SWAT or Infra-Purple know and it can be enabled for your repo.

name: 'Build and Publish npm Package'

on:
  # This workflow will run for the PR events:
  #   opened/reopened: A PR is opened/re-opened,
  #   synchronize: The PR's head branch is updated (commits pushed, the base branch changed or the head is updated from the base branch)
  #   closed: A PR is merged or closed (The examine-triggers job makes sure we only run if a merge happened, not when a close happens)
  pull_request:
    # TODO: This will create a new npm package for each push to the PR, determine if that is the desired behavior or if you only
    #        want a package created when a merge to main happens.
    types: [opened, reopened, synchronize, closed]

    # TODO: If there are multiple projects in the repo, add the path to the npm package project so changes to those projects don't trigger this workflow
    #        If the repo only contains the npm package project, delete the paths:
    paths:
      - ''

env:
  TIMEZONE: 'america/denver'
  REPO_URL: '${{ github.server_url }}/${{ github.repository }}'

jobs:
  examine-triggers:
    runs-on: ubuntu-latest
    outputs:
      CONTINUE_WORKFLOW: ${{ env.CONTINUE_WORKFLOW }}
      REF_TO_BUILD_AND_TAG: ${{ env.REF_TO_BUILD_AND_TAG }}
      CREATE_RELEASE: ${{ env.CREATE_RELEASE }}
      IS_PRERELEASE: ${{ env.IS_PRERELEASE }}
      DIST_TAG: ${{ env.DIST_TAG }}

    steps:
      - name: Set default env variables
        uses: actions/github-script@v6
        with:
          script: |
            const targetRef = '${{ github.base_ref }}';
            const sourceRef = '${{ github.head_ref }}';
            const mergeRef = '${{ github.ref }}';
            const prIsDraft = '${{ github.event.pull_request.draft }}' === 'true';
            const prClosed = '${{ github.event.action }}' === 'closed';
            const prMerged = prClosed && '${{ github.event.pull_request.merged }}' === 'true';
            const prMergedToMain = prMerged && targetRef === 'main';
            const isPreRelease = !prMergedToMain;
            // For a detailed explanation of why we use different refs for different scenarios 
            // see https://docs.github.com/en/rest/reference/pulls#get-a-pull-request
            const refToBuildAndTag = prMergedToMain ? mergeRef : sourceRef;
            const continueWorkflow = prClosed && !prMerged ? false : true;
            const doTagRelease = continueWorkflow && !prIsDraft ? true :  false;
            core.exportVariable('IS_PRERELEASE', isPreRelease);
            core.exportVariable('REF_TO_BUILD_AND_TAG', refToBuildAndTag);
            core.exportVariable('CONTINUE_WORKFLOW', continueWorkflow);
            core.exportVariable('CREATE_RELEASE', doTagRelease);
            core.exportVariable('DIST_TAG', prMergedToMain ? 'latest' : sourceRef)

  build-and-publish-to-gpr:
    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners
    needs: [examine-triggers]
    if: needs.examine-triggers.outputs.CONTINUE_WORKFLOW == 'true'

    env:
      IS_PRERELEASE: ${{ needs.examine-triggers.outputs.IS_PRERELEASE }}
      DIST_TAG: ${{ needs.examine-triggers.outputs.DIST_TAG }}
      REF_TO_BUILD_AND_TAG: ${{ needs.examine-triggers.outputs.REF_TO_BUILD_AND_TAG }}

    defaults:
      run:
        shell: bash
        working-directory: '' # TODO: Add the path to the npm package project

    outputs:
      NEXT_VERSION: ${{ steps.version.outputs.NEXT_VERSION }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.REF_TO_BUILD_AND_TAG }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16 # TODO: verify node version
          registry-url: https://npm.pkg.github.com/

      # TODO: If the project contains dependencies to other npm packages in GitHub's npm package registry, uncomment this step, otherwise delete
      # - name: Authenticate with GitHub Packages for Restoring Packages
      #   uses: im-open/authenticate-with-gh-package-registries@v1.0
      #   with:
      #     read-pkg-token: ${{ secrets.READ_PKG_TOKEN }} # This is an org-level secret
      #     orgs: 'im-client,im-enrollment,im-practices' # TODO: Verify list of orgs packages will be pulled from

      - name: Calculate next version
        id: version
        uses: im-open/git-version-lite@v2.2
        with:
          calculate-prerelease-version: ${{ env.IS_PRERELEASE }}
          branch-name: ${{ github.head_ref }} # This is only populated when the trigger is pull_request, otherwise it is empty
          tag-prefix: 'none' # TODO: verify your prefix, the new ci workflows add v automatically but npm packages typically won't have a prefix

      # TODO: Add any additional flags you need to version your project like --allow-same-version
      - run: npm version ${{ steps.version.outputs.NEXT_VERSION }}

      # TODO: Add any additional flags you need to restore packages in  your project like --ignore-scripts
      # TODO: For some projects you may need several commands, one to do this at the root, one to change directories and one to do it in the package dir
      - run: npm ci

      # TODO: If you have tests that run for the npm package, add a new run step with the appropriate npm command
      # - run: npm run tests

      - name: reset .npmrc for publishing
        run: npm set //npm.pkg.github.com/:_authToken '${{ secrets.GITHUB_TOKEN }}'

      - run: npm publish --tag ${{ env.DIST_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo

      - name: Create GitHub Tag and Release
        if: needs.examine-triggers.outputs.CREATE_RELEASE == 'true'
        id: create_release
        uses: im-open/create-release@v3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          delete-existing-release: true # Handy when you hit 're-run jobs' on a workflow run
          tag-name: ${{ steps.version.outputs.NEXT_VERSION }}
          prerelease: ${{ env.IS_PRERELEASE }}
          commitish: ${{ env.REF_TO_BUILD_AND_TAG }}

  cleanup-prereleases:
    if: always() && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup the branch pre-releases for all closed PRs
        uses: im-open/delete-prereleases-for-branch@v1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: ${{ github.head_ref }}

      - name: Cleanup pre-release packages
        if: always()
        uses: im-open/delete-branch-package-versions@v2.2
        with:
          github-token: ${{ secrets.GH_PACKAGES_TOKEN }} # This is a special org-level secret that needs to be authorized for this repo
          organization: ${{ github.repository_owner }}
          branch-name: ${{ github.head_ref }}
          package-type: 'npm'
          package-names: '' # TODO: Add comma separated list of packages to delete (the base name without any versions, like IdentityCient or Mktp.Logging)

  finish-build:
    if: always() && needs.examine-triggers.outputs.CONTINUE_WORKFLOW == 'true'
    needs: [examine-triggers, build-and-publish-to-gpr]
    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners
    env:
      NEXT_VERSION: ${{ needs.build-and-publish-to-gpr.outputs.NEXT_VERSION }}

    steps:
      - uses: im-open/workflow-conclusion@v2.1
        id: conclusion
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo

      - name: Send Status to Teams
        if: always()
        uses: im-open/post-status-to-teams-action@v1.3
        with:
          title: 'Build and Publish <project-name> to GH Packages' # TODO: Replace <project-name>
          workflow-status: ${{ steps.conclusion.outputs.workflow_conclusion }}
          workflow-type: Build
          teams-uri: ${{ secrets.MS_TEAMS_URI }} # This is a repo-level secret
          timezone: ${{ env.TIMEZONE }}
          custom-facts: |
            [
              { "name": "Workflow", "value": "${{ github.workflow }}" },
              { "name": "Run", "value": "${{ github.run_number }}" },
              { "name": "Actor", "value": "${{ github.actor }}" },
              { "name": "Version", "value": "${{ env.NEXT_VERSION }}" }
            ]

      - name: Comment on PR with version ${{ env.NEXT_VERSION }}
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          script: |
            let nextVersion = '${{ env.NEXT_VERSION }}';

            let tagText = '- Tag - N/A';
            let testPackageText = '';
            if (nextVersion && nextVersion.length > 0) {
              tagText =  `- [Tag - ${nextVersion}](${{ env.REPO_URL }}/releases/tag/${nextVersion})`;
              testPackageText = `- To test this version try running:
              \`\`\`bash
              npm install @<org>/<package-name>@${nextVersion} # TODO: Replace <org>/<package-name> with actual values
              \`\`\`
            `;
            }

            const commentBody = `
            - [Workflow Run - ${{ steps.conclusion.outputs.workflow_conclusion }}](${{ env.REPO_URL }}/actions/runs/${{ github.run_id }})
            ${tagText}
            ${testPackageText}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      - name: Check for Failures
        if: steps.conclusion.outputs.workflow_conclusion == 'failure'
        run: |
          echo "There were errors in the workflow.  Check the workflow-conclusion step above for more details on what failed."
          exit 1
