# Workflow Code: GiddyBuzzard_v15    DO NOT REMOVE
# Purpose:
#    The main purpose of this workflow is to verify that the database can be created, all of the migration scripts can be run, and any tests that exist pass.
#    In addition to that, however, there are three other things this workflow template is set up to do.
#      1. Create snapshots. Snapshots are create sql object (table, view, sproc, etc.) scripts that show the shape of an object and can be
#         useful for keeping a historical record in GitHub of the changes to them.
#      2. Create a backup of the database and store it for later consumption. The backup can then be used in a workflow to circumvent the need
#         to spin up the database from scratch. Very helpful for decreasing build times. Please note however that this is only a backup of a local database.
#         It does not take the place of backups that should be happening of Production databases.
#      3. Create mock sql objects that can be consumed by other database repos' CI processes. A flag on the build database step in this workflow can be set
#         so that your database's dependencies are downloaded and installed.
#
#    The need for creating snapshots and backups in this workflow is not a very common need. They are here in case you need them, but likely you won't.
#    There are TODO's throughout this template that let you know when something isn't necessary if you don't want snapshots and/or backups created.
#
#    Creating mock sql objects is a bit less rare of a need, but only if your database is a sectioned off part of the legacy ExtendHealth monolith. Again,
#    there will be TODO's showing you where some items can be removed if you don't have any dependencies and/or don't need to create mock objects to be
#    consumed by others.
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    - Azure SQL Database (Core Template)
#    - On-Prem Database   (Core Template)

name: Build Database CI
# TODO: Select the appropriate trigger, if push and pull are both included, two builds will be kicked off when a PR exists and a new commit is pushed to the corresponding branch.
on:
  # This workflow will run for the PR events:
  # opened/reopened: A PR is opened/re-opened,
  # synchronize: The PR's head branch is updated (commits pushed, the base branch changed or the head is updated from the base branch)
  # closed: A PR is merged or closed (The triggers job makes sure we only run if a merge happened, not when a close happens)
  pull_request:
    types: [opened, reopened, synchronize, closed]
env:
  DB_NAME: '' # TODO: Fill in your repo's database name
  DB_SERVER_NAME: 'localhost'
  DB_SERVER_PORT: '1433'
  DEFAULT_BRANCH: 'main' # TODO: verify default branch name
  GITHUB_PACKAGE_URL: 'https://nuget.pkg.github.com' # TODO: This can be removed if your database doesn't have any dependency objects stored in GitHub Packages
  GITHUB_PACKAGE_SOURCE_URL: '${{ env.GITHUB_PACKAGE_URL }}/${{ github.repository_owner }}/index.json'

  # TODO: The following are all for the snapshot step below and can be removed if it's not used
  SNAPSHOT_PATH: './snapshot' # TODO: Verify this path is correct
  EXCLUDED_DB_SNAPSHOT_OBJECTS: '' # TODO: Add some comma separated values to this

  # TODO: These next variables are for backing up the database. Remove if not needed.
  BACKUP_PATH: '' # TODO: The path on the action runner to put the backup path
  BACKUP_FILENAME: '' # TODO: The name to give the backup file

jobs:
  # TODO: If you don't need to create snapshots, backups, or mock objects then this whole job can be removed. Make sure to update the 'needs' of later jobs accordingly.
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      last-commit-is-snapshot: ${{ steps.capture-branch-state.outputs.isSnapshot }} # TODO: Can be useful for if logic to skip steps. Remove if this isn't something you need to branch on.
      current-branch-is-default: ${{ steps.capture-branch-state.outpus.isDefaultBranch }} # TODO: Can be useful for if logic to skip steps. Remove if your CI process is the same for all branches.
      should-skip-remaining-workflow-jobs: ${{ steps.capture-branch-state.outputs.skip }} # TODO: This is only needed if your workflow is committing a snapshot and needs to skip running the CI for that commit. Remove this and its usages if not needed.
    steps:
      - uses: actions/checkout@v3

      # TODO: Update or remove this if you aren't creating snapshots and/or are doing the same CI process for every branch.
      - name: Capture branch details
        id: capture-branch-state
        shell: pwsh
        run: |
          $CurrentBranch = git rev-parse --abbrev-ref HEAD
          $LastCommitBy = git --no-pager show -s --format="%aN"
          $CurrentBranchIsDefault = ($CurrentBranch -eq "${{ env.DEFAULT_BRANCH }}")
          $LastCommitIsSnapshot = ($LastCommitBy -eq "github-actions")

          echo "::set-output name=isDefaultBranch::$CurrentBranchIsDefault"
          echo "::set-output name=isSnapshot::$LastCommitIsSnapshot"

          if ($LastCommitIsSnapshot -and !$CurrentBranchIsDefault)
          {
            Write-Host "Snapshot was last commit, skipping the other jobs"
            echo "::set-output name=skip::true"
          }
          else
          {
            Write-Host "Snapshot was not the last commit, continuing with the other jobs"
            echo "::set-output name=skip::false"
          }

  # TODO: Remove this linting job if your project doesn't need/want it
  lint-migration-files:
    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners
    needs: set-vars # TODO: Remove this if you deleted the set-vars job
    if: ${{ needs.set-vars.outputs.should-skip-remaining-workflow-jobs == 'false' }} # TODO: Remove this if there is no snapshot commit that should cause this step to be skipped.
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14' # TODO: The current LTS version. Can be updated to something else if needed.

      - id: migration-folder
        shell: pwsh
        run: echo "::set-output name=folder::$($(Get-Date).Year).$($(Get-Date).Month.ToString("00"))"
      - name: SQL Lint
        uses: im-open/tsql-lint-action@v1.1
        with:
          tsqllint-version: 1.11.0
          path-to-sql-files: 'Database/src/SqlDatabase/Migrations/${{ steps.migration-folder.outputs.folder }}' # TODO: Update this path to wherever the files to lint live
          file-name-filter: 'V9*.sql' # TODO: Update this if necessary
          path-to-lint-config: ./.tsqllintrc # TODO: Update this with the path to your project's .tsllintrc file

  build-database:
    runs-on: [self-hosted, im-linux]
    needs: [set-vars, lint-migration-files] # TODO: Remove any jobs you deleted above
    if: ${{ needs.set-vars.outputs.should-skip-remaining-workflow-jobs == 'false' }} # TODO: Remove this if there is no snapshot commit that should cause this step to be skipped.
    
    env:
      SQL_SERVER_PASSWORD: 'StrongPassword!1'
      
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        options: -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=StrongPassword!1"
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Flyway
        uses: im-open/setup-flyway@v1.1
        with:
          version: 7.2.0 # This version works with the current version of build-database-ci-action. Newer versions might, but they should be tested.

      - name: Build Database
        uses: im-open/build-database-ci-action@v3.2
        with:
          # TODO: These parameters are the most commonly used. They tell the action to create the repo's database on the Action Runner,
          #       validate and run the repo's migration scripts, run tests, and seed data into the database for future needs (like integration tests).
          #       There is more configuration for the action that can happen though, and more it can do.
          #       See https://github.com/im-open/build-database-ci-action for detailed documentation and examples.
          db-server-name: ${{ env.DB_SERVER_NAME }}
          db-name: ${{ env.DB_NAME }}
          create-database-file: '' # TODO: Add the path to the create database file (often called Initialization.sql)
          migration-files-path: '' # TODO: Add the path to the directory with your migration files
          should-validate-migrations: true # This will make flyway validate the migration scripts before running them
          run-tests: true
          test-files-path: '' # TODO: Add the path to the directory with your test files
          seed-data: true
          seed-data-files-path: '' # TODO: Add the path to the directory with your seed data files
          use-integrated-security: false
          db-username: 'sa' # The default system administrator account that comes with SQL Server. This is the only account set up in our self hosted Action Runners' SQL Server instances.
          db-password: ${{ env.SQL_SERVER_PASSWORD }}


      #########################################################################################################################
      # The previous three steps are all that most builds will need. They will build your database on the Action Runner and run any tests you have.
      # The following steps are for the three activities mentioned at the start of this template.
      #   1. Creating snapshots
      #   2. Creating mock sql objects
      #   3. Creating a backup
      # Remove the ones that are unnecessary for your repo's CI process.
      #########################################################################################################################

      # The next four steps can be removed if your build doesn't need to create snapshots of database objects.
      # Otherwise they can be uncommented and the TODO's addressed.
      # TODO: Replace what is in this step with what your build needs in order to determine what database objects have changed
      # The output is a json string containing a list of objects with the following properties (see https://github.com/im-open/increment-database-object-snapshots#inputs for more information)
      #   * objectName
      #   * schemaName
      #   * objectType
      #   * operationType
      # - name: Get db objects that have changed
      #   id: changed-objects
      #   shell: pwsh
      #   run: |
      #     $changedObjectsQuery =
      #       "SELECT
      #           objectId,
      #           schemaName,
      #           objectName,
      #           CASE objectType
      #             WHEN 'U' THEN 'Tables'
      #             WHEN 'V' THEN 'Views'
      #             WHEN 'P' THEN 'StoredProcedures'
      #             WHEN 'SO' THEN 'Sequences'
      #             WHEN 'TF' THEN 'UserDefinedFunctions'
      #             WHEN 'FN' THEN 'UserDefinedFunctions'
      #             WHEN 'IF' THEN 'UserDefinedFunctions'
      #             WHEN 'SN' THEN 'Synonyms'
      #             ELSE objectType
      #           END AS objectType,
      #           operationType
      #         FROM DBA.V_ChangedObjectsForSnapshot"

      #     $changedObjects = Invoke-Sqlcmd -ServerInstance "${{ env.DB_SERVER_NAME }}" -Database "${{ env.DB_NAME }}" -Query $changedObjectsQuery
      #     $mappedObjects = $changedObjects | foreach-object { @{ schemaName=$_.schemaName; objectName=$_.objectName; objectType=$_.objectType; operationType=$_.operationType } }
      #     $objectsAsJson = $mappedObjects | ConvertTo-Json -Compress

      #     echo "::set-output name=json::$objectsAsJson"

      # - name: Increment snapshots
      #   uses: im-open/increment-database-object-snapshots@v1.0
      #   with:
      #     db-name: ${{ env.DB_NAME }}
      #     instance-name: ${{ env.DB_SERVER_NAME }}
      #     snapshot-path: ${{ env.SNAPSHOT_PATH }}
      #     objects-to-increment: '${{ steps.changed-objects.outputs.json }}'
      #     excluded-db-objects: ${{ env.EXCLUDED_DB_SNAPSHOT_OBJECTS }}

      # - name: Setup git for snapshot commit
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com

      # TODO: Update the commit message if desired
      # - name: Commit the snapshots
      #   run: |
      #     git add ${{ env.SNAPSHOT_PATH }}
      #     git commit -m "Automated Snapshot Commit"
      #     git push -f origin HEAD

      ##### End of snapshot steps #####

      
      # This allows the next steps to authenticate with and push to GitHub Packages.
      # If you aren't using the steps below you can remove this one.
      # - name: Authenticate with GitHub Packages
      #   uses: im-open/authenticate-with-gh-package-registries@v1.0
      #   with:
      #     read-pkg-token: ${{ secrets.READ_PKG_TOKEN }}  # This is an org-level secret
      #     orgs: 'im-practices,im-client' # TODO: Verify list of orgs packages will be pulled from

      # Remove this if you don't need to publish mock sql objects
      # - name: Create and publish views from tables
      #   uses: im-open/sql-view-to-table-generator@v1.1
      #   with:
      #     schema-names: 'dbo,CustomSchema' # TODO: Replace this with an actual list
      #     db-name: ${{ env.DB_NAME }}
      #     db-server: ${{ env.DB_SERVER_NAME }}
      #     default-branch: ${{ env.DEFAULT_BRANCH }}
      #     nuget-retrieval-url: ${{ env.GITHUB_PACKAGE_SOURCE_URL }}
      #     publish-packages: true
      #     nuget-publish-url: ${{ env.GITHUB_PACKAGE_SOURCE_URL }}
      #     nuget-api-key: '${{ secrets.GITHUB_TOKEN }}' # Special per-job token generated by GH for interacting with the repo
      #     repository-url: ${{ github.repositoryUrl }}

      # TODO: This is needed only if you have to update what objects have changed so it can be used in another step like changed-objects.
      #       Remove or update as needed.
      # - name: Update database object versions
      #   shell: pwsh
      #   run: |
      #     $updateObjectVersionsSQL = "EXEC DBA.usp_UpdateCheckSumForChangedObjectDefinitions;"
      #     Invoke-Sqlcmd -ServerInstance "${{ env.DB_SERVER_NAME }}" -Database "${{ env.DB_NAME }}" $updateObjectVersionsSQL

      # TODO: Remove this if your build doesn't need to create/publish backup files
      # - name: Create and publish backup files
      #   uses: im-open/create-and-publish-db-backup-file@v1.1
      #   with:
      #     db-server: ${{ env.DB_SERVER_NAME }}
      #     db-name: ${{ env.DB_NAME }}
      #     backup-path: '${{ env.BACKUP_PATH }}' # This can be changed if needed
      #     backup-name: '${{ env.BACKUP_FILENAME }}'
      #     version: '1.1.${{ github.run_number }}' # TODO: Set to 1.1.*** in order to not conflict with previous versions from Teamcity. Update this if desired.
      #     nuget-source-url: ${{ env.GITHUB_PACKAGE_SOURCE_URL }}
      #     nuget-api-key: '${{ secrets.GITHUB_TOKEN }}' # Special per-job token generated by GH for interacting with the repo
      #     repository-url: ${{ github.repositoryUrl }}
      #     authors: '' # TODO: This will get put in the .nuspec file. It should be updated with your team name or something similar.
