# Workflow Code: SparklyToad_v5    DO NOT REMOVE
# Purpose:
#    Publishes a techdocs site to the storage account where TechHub
#    looks for TechDocs.
#
# Frequency:
#    - This workflow can be used once per TechDocs site or can be combined
#      to publish multiple docs at once
#
# Projects to use this Template with:
#    - Any project with TechDocs

name: Publish TechDocs Site

# TODO:  Select the appropriate triggers for when TechDocs should be published
on:
  push:
    branches:
      - main
  # workflow_dispatch:
  # pull_request:
  #   types: [closed]

permissions:
  # Required for secretless azure access and deploys
  id-token: write
  contents: read

jobs:
  publish-techdocs-site:
    uses: im-practices/.github/.github/workflows/im-reusable-publish-techdocs.yml@v3
    with:
      # The working directory where mkdocs.yaml is located
      working-directory: '' # TODO: specify the working directory

      # The repo branch, tag or sha that the TechDocs will be built and published from
      ref-to-build-and-publish: ${{ github.ref }} # TODO:  This may need to be modified depending on the trigger.
      #   merge commit or push: github.ref
      #   pull_request non-merge commit: github.head_ref
      #   workflow_dispatch => inputs.ref

      # The TechHub entity that the docs sites belongs to in the format 'default/<kind>/<entity-name>'
      entity-name: 'default/<kind>/<entity-name>' # TODO:  Replace kind and entity name

      # Flag that determines where the TechDocs will be published
      # When true the TechDocs are published to TechHub's UAT and Prod containers
      # When false the TechDocs are only published to TechHub's UAT container
      is-production-ready: true # TODO: This may need to be dynamically set based on the trigger

      # Optional inputs with their defaults
      # runs-on: im-techdocs      # im-techdocs is purpose-built for techdocs sites, use this runner unless there is a specific reason not to.
      # github-environment: prod  # the environment that the SP info (ARM_CLIENT_ID, ARM_SUBSCRIPTION_ID) will be pulled from.
