# Workflow Code: PitifulPelican_v12    DO NOT REMOVE
# Purpose:
#    Automatically cleans up inactive cards on a project's deployment board
#    when it runs at its scheduled time or when someone kicks it off manually.
#
#  Frequency:
#    - This workflow should only be used once per repository.  This workflow
#      uses a matrix strategy so if the repo reports statuses to multiple boards
#      they can be added to the matrix below.
#
# Projects to use this Template with:
#    - Azure App Service or Function  (Core Template)
#    - Azure SQL Database             (Core Template)
#    - Storage Account Deployments    (Core Template)
#    - On-Prem Service                (Core Template)
#    - On-Prem Site                   (Core Template)
#    - On-Prem Database               (Core Template)
#    - Terraform                      (Core Template)

name: Cleanup Automated Deployment Board

# See the following site for help creating the right cron syntax: https://crontab.guru/
# The cron job is specified in UTC.
on:
  schedule:
    - cron: '30 6 * * 0' # Every Sunday at 06:30 UTC
  workflow_dispatch:

jobs:
  cleanup-board:
    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners

    # Inactive cards are the only thing this workflow will cleanup
    # Inactive cards are not currently deployed and do not have an open branch associated with them.
    #
    # Foreach release type (branch/tag/sha) you need to specify
    # 1- A strategy for the cleanup.  It can be age or number.
    #    Age: The max age in days an inactive card can be
    #    Number: The max number of inactive releases to keep
    # 2 - Threshold.  This is a positive whole number representing either the max age in days or the number of releases to keep.
    #     This threshold does not include any of the active cards.  It only applies to the inactive ones.
    #
    # See https://github.com/im-open/cleanup-deployment-board/ for more information

    strategy:
      matrix:
        include:
          # TODO: If the repo has more than one project board, include another set (- board-number through sha-threshold) below
          - board-number: 1 # TODO: verify the number of your board
            branch-strategy: '' # age|number
            branch-threshold: '' # positive whole number representing max age in days or number of inactive releases to keep
            tag-strategy: '' # age|number
            tag-threshold: '' # positive whole number representing max age in days or number of inactive releases to keep
            sha-strategy: '' # age|number
            sha-threshold: '' # positive whole number representing max age in days or number of inactive releases to keep

    steps:
      - name: Cleanup
        uses: im-open/cleanup-deployment-board@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          board-number: ${{ matrix.board-number }}

          branch-cleanup-strategy: ${{ matrix.branch-strategy }}
          branch-threshold: ${{ matrix.branch-threshold }}

          tag-cleanup-strategy: ${{ matrix.tag-strategy }}
          tag-threshold: ${{ matrix.tag-threshold }}

          sha-cleanup-strategy: ${{ matrix.sha-strategy }}
          sha-threshold: ${{ matrix.sha-threshold }}
