# Workflow Code: SparklyToad_v1    DO NOT REMOVE
# Purpose:
#    Publishes a techdocs site to the storage account where TechHub
#    looks for TechDocs.
#
# Frequency:
#    - This workflow can be used once per TechDocs site or can be combined
#      to publish multiple docs at once
#
# Projects to use this Template with:
#    - Any project with TechDocs 

name: Publish TechDocs Site

on:
  push:

jobs:
  publish-techdocs-site:
    runs-on: [self-hosted, ubuntu-20.04]
    services:
      kroki:
        image: yuzutech/kroki
        ports:
          - 8000:8000

    environment: prod

    env:
      # These items will remain the same for all workflows
      ACCOUNT_NAME: bdaimpna26techhubsa
      CONTAINER_NAME: techdocs

      # This is project dependent.  
      # TODO:  Replace kind and entity name based on the entity this techdocs site will belong to.
      #        The name can be found in catalog-info.yaml.
      ENTITY_NAME: 'default/<add-kind>/<add-entity-name>'
      
      
      # These AZURE env variables must be set in order to publish the techdocs site.  All 
      # SPs that are owners of their rgrp's have access to publish to bdaimpna26techhubsa.
      # Teams can use their own SP to deploy to the storage account.
      # TODO:  Ensure these secrets are set
      AZURE_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
      AZURE_CLIENT_ID: '${{ secrets.ARM_CLIENT_ID }}'
      AZURE_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: |
          python -m pip install mkdocs-techdocs-core==1.*
          python -m pip install mkdocs-build-plantuml-plugin==1.*
          python -m pip install mkdocs-kroki-plugin

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # TODO:  Verify this secret is set

      # Note: If there are multiple TechDocs sites for this repo, this step can be duplicated
      #       and multiple sites can be published from one workflow.  Each step will have a 
      #       different working directory and a different --entity argument.
      - name: Generate TechDocs Site
        working-directory: '' # TODO:  specify the working directory where the mkdocs.yaml file is located
        run: |
          techdocs-cli generate --no-docker --verbose
          techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName ${{ env.ACCOUNT_NAME }} --storage-name ${{ env.CONTAINER_NAME }} --entity ${{ env.ENTITY_NAME }}

      # TODO: To publish additional sites, 
      #       1 - Duplicate the 'Generate TechDocs Site' step
      #       2 - Update the working directory to a different location
      #       3 - Provide a different --entity argument
      