# Workflow Code: ScornfulFlamingo_v4   DO NOT REMOVE
# Purpose:
#    Deletes a blob from a specified Azure Storage Account when someone kicks it off manually.
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    - Storage Account Deployments (Core Template)
#
# TODO: Prerequisites:
#    - Ensure each of the repo-level and env-level secrets used in this workflow have been populated by an admin in your repository.
#    - The SP used in this workflow needs an additional permission (StorageBlob Data Contributor) so it can delete blobs
#      https://docs.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access?tabs=portal

name: Delete Azure Blob
run-name: Delete ${{ inputs.environment }} blob ${{ inputs.blob-name }}
# TODO: Evaluate the appropriate triggers
on:
  workflow_dispatch:
    inputs:
      storage-account-name:
        description: The name of the storage account where the blob to delete lives
        required: true
      container-name:
        description: The name of the storage account container where the blob to delete lives
        required: true
      blob-name:
        description: The name of the blob to delete
        required: true
      environment:
        description: The environment to delete the blob from
        required: true
        type: choice
        options: # TODO: Update for the environments that are available
          - dev
          - qa
          - stage
          - demo
          - uat
          - prod

jobs:
  delete-blob:
    runs-on: [self-hosted, ubuntu-20.04]

    environment: ${{ github.event.inputs.environment }}

    steps:
      - run: |
          echo $'
          | Build Arguments | Value                                             |
          | ---             |  ---                                              |
          | Environment     | `${{ github.event.inputs.environment }}`          |
          | Storage Acct    | `${{ github.event.inputs.storage-account-name }}` |
          | Container       | `${{ github.event.inputs.container-name }}`       |
          | Blob Name       | `${{ github.event.inputs.blob-name }}`            |' >> $GITHUB_STEP_SUMMARY
          
      - name: AZ Login
        id: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # This is an env-level secret

      # This call uses RBAC (--auth-mode login) to delete files from the azure storage account.
      # No other key or connection string is needed. In order to delete files from a stg account
      # the SP that authenticates in the step above needs an additional permission (Storage
      # Blob Data Contributor).  Without that permission, this call will not succeed.
      # https://docs.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access?tabs=portal
      - name: Delete Blob
        run: |
          az storage blob delete \
            --auth-mode login \
            --account-name '${{ github.event.inputs.storage-account-name }}' \
            --container-name '${{ github.event.inputs.container-name }}' \
            --name '${{ github.event.inputs.blob-name }}'

      - name: Azure logout
        if: always() && steps.login.outcome == 'success'
        run: |
          az logout
          az cache purge
          az account clear
