# Workflow Code: FrazzledFerret_v27    DO NOT REMOVE
# Purpose:
#    Removes a lock from the terraform state when someone kicks it off manually.
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    - Terraform (Core Template)
#
# TODO Prerequisites
#    - Ensure each of the repo-level and env-level secrets used in this workflow have been populated by an admin in your repository.

name: Unlock Terraform State
run-name: Unlock state in ${{ inputs.environment }} with id ${{ inputs.lock-id }}
on:
  workflow_dispatch:
    inputs:
      lock-id:
        description: The lock ID that needs to be removed.  Terraform provides this value (lock info.ID) in the message indicating there was an error acquiring the state lock.
        required: true
      environment:
        description: The environment the lock should be removed in
        required: true
        type: choice
        options: # TODO: Update for the environments that are available
          - dev
          - qa
          - stage
          - demo
          - uat
          - prod
      branch-tag-sha:
        description: The branch, tag or sha of the terraform that is currently in the environment where the lock is.  This is needed to do a terraform init with the appropriate code.
        required: true

permissions:
  # Required for secretless azure access and deploys
  id-token: write
  contents: read

env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  GITHUB_REF: ${{ github.event.inputs.branch-tag-sha  }}
  # The following ARM_* values are env-level secrets/variables
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }} # This is an org-level variable
  ARM_ENVIRONMENT: 'public'
  TF_IN_AUTOMATION: 'true'
  TF_VERSION: '~>1.4.0' #TODO:  Verify your version of terraform.
  TF_WORKING_DIR: './infrastructure/${{ github.event.inputs.environment }}' # TODO: Verify this directory is correct for your repository (older projects may not be inside of an infrastructure folder)
  # The following SSH_* secrets are org-level secrets
  SSH_KEY_STORAGE_ACCOUNT: ${{ secrets.SSH_STORAGE_ACCOUNT }}
  SSH_KEY_NETWORK_INFO: ${{ secrets.SSH_NETWORK_INFO }}
  SSH_DEPLOY_KEY_INFO: |
    [
      { "orgAndRepo": "im-platform/storage-account-network-rules", "envName" : "SSH_KEY_STORAGE_ACCOUNT" },
      { "orgAndRepo": "im-platform/network-information", "envName" : "SSH_KEY_NETWORK_INFO" }
    ]

jobs:
  tf-unlock-state:
    runs-on: im-linux
    environment: ${{ github.event.inputs.environment }} # Use inputs context because env context is not available to environment:

    defaults:
      run:
        shell: bash
        working-directory: '${{ env.TF_WORKING_DIR }}'

    steps:
      - run: |
          echo $'
          | Build Arguments | Value                                |
          | ---             |  ---                                 |
          | Lock ID         | `${{ github.event.inputs.lock-id }}` |
          | Environment     | `${{ env.ENVIRONMENT }}`             |
          | Branch/Tag/Sha  | `${{ env.GITHUB_REF }}`              |' >> $GITHUB_STEP_SUMMARY

      - name: Set Variables
        id: set-variables
        uses: im-open/set-environment-variables-by-scope@v1.2
        with:
          scope: ${{ inputs.environment }}
        env:
          # TODO: For the following inputs, fill in the value if you have the environment or delete the environment if it does not exist
          RESOURCE_GROUP@dev: ''
          RESOURCE_GROUP@qa: ''
          RESOURCE_GROUP@stage: ''
          RESOURCE_GROUP@demo: ''
          RESOURCE_GROUP@uat: ''
          RESOURCE_GROUP@prod: ''
          APP_INSIGHTS_NAME@dev: ''
          APP_INSIGHTS_NAME@qa: ''
          APP_INSIGHTS_NAME@stage: ''
          APP_INSIGHTS_NAME@demo: ''
          APP_INSIGHTS_NAME@uat: ''
          APP_INSIGHTS_NAME@prod: ''

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      # Allows pulling modules from the repo instead of artifactory
      - name: Setup SSH Keys and known_hosts
        uses: im-open/setup-deploy-keys@v1.2
        with:
          deploy-key-info: ${{ env.SSH_DEPLOY_KEY_INFO }}

      - name: AZ Login
        uses: azure/login@v2
        with:
          # This is an org-level variable
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          # These are env-level variables
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
          client-id: ${{ vars.ARM_CLIENT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '${{ env.TF_VERSION }}'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Unlock State
        run: terraform force-unlock -force ${{ github.event.inputs.lock-id }}

      - name: Annotate App Insights
        uses: im-open/create-app-insights-annotation@v1.0
        with:
          subscriptionId: ${{ vars.ARM_SUBSCRIPTION_ID }} # This is an env-level variable
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          appInsightsResourceName: '${{ env.APP_INSIGHTS_NAME }}'
          category: 'Runbook'
          customMetadata: 'Action=UnlockTfState,LockId=${{ inputs.lock-id }},RunBy=${{ github.actor }},RunID=${{ github.run_id }}'

      - name: Send Unlock TF State Event to PagerDuty
        if: always()
        uses: im-open/pagerduty-change-events-action@v1.1
        with:
          integration-key: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }} # This is an env-level secret  # TODO:  Ensure an integration has been created in PagerDuty on each applicable service and the secret added to the environment
          custom-event: '[Runbook] Terraform State unlocked in ${{ env.RESOURCE_GROUP }} (${{ job.status }})'

      - name: Azure logout
        run: |
          az logout
          az cache purge
          az account clear
