# Workflow Code: GratefulTermite_v18    DO NOT REMOVE
# Purpose:
#    Taints a specified terraform resource when someone kicks it off manually.
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    -  Terraform (Optional Template)
#
# TODO Prerequisites:
#    - Ensure each of the repo-level and env-level secrets used in this workflow have been populated by an admin in your repository.

name: Taint Terraform Resource
run-name: Taint ${{ inputs.environment }} resource${{ inputs.tf-resource-address }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment the taint should be done in.
        required: true
        type: choice
        options: # TODO: Update for the environments that are available
          - dev
          - qa
          - stage
          - demo
          - uat
          - prod
      # This is required because a tf init has to be performed before the terraform taint command
      branch-tag-sha:
        description: The branch, tag or sha of the terraform that has the configuration for the resource to taint.
        required: true
      tf-resource-address:
        description: The address of the resource to taint. E.g. module.my-module.azurerm_mssql_server.server
        required: true

permissions:
  # Required for secretless azure access and deploys
  id-token: write
  contents: read

env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  GITHUB_REF: ${{ github.event.inputs.branch-tag-sha  }}
  # The following ARM_* values are env-level secrets/variables
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }} # This is an org-level variable
  ARM_ENVIRONMENT: 'public'
  TF_IN_AUTOMATION: 'true'
  TF_VERSION: '~>1.4.0' #TODO:  Verify your version of terraform.
  TF_WORKING_DIR: './infrastructure/${{ github.event.inputs.environment }}' # TODO: Verify this directory is correct for your repository (older projects may not be inside of an infrastructure folder)
  # The following SSH_* secrets are org-level secrets
  SSH_KEY_STORAGE_ACCOUNT: ${{ secrets.SSH_STORAGE_ACCOUNT }}
  SSH_KEY_NETWORK_INFO: ${{ secrets.SSH_NETWORK_INFO }}
  SSH_DEPLOY_KEY_INFO: |
    [
      { "orgAndRepo": "im-platform/storage-account-network-rules", "envName" : "SSH_KEY_STORAGE_ACCOUNT" },
      { "orgAndRepo": "im-platform/network-information", "envName" : "SSH_KEY_NETWORK_INFO" }
    ]

jobs:
  tf-taint-resource:
    runs-on: [self-hosted, im-linux]
    environment: ${{ github.event.inputs.environment }} # Use inputs context because env context is not available to environment:

    defaults:
      run:
        shell: bash
        working-directory: '${{ env.TF_WORKING_DIR }}'

    steps:
      - run: |
          echo $'
          | Build Arguments     | Value                                            |
          | ---                 |  ---                                             |
          | Environment         | `${{ env.ENVIRONMENT }}`                         |
          | Branch/Tag/Sha      | `${{ env.GITHUB_REF }}`                          |
          | TF Resource Address | `${{ github.event.inputs.tf-resource-address }}` |' >> $GITHUB_STEP_SUMMARY
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      # Allows pulling modules from the respective github repo instead of artifactory
      - name: Setup SSH Keys and known_hosts
        uses: im-open/setup-deploy-keys@v1.1
        with:
          deploy-key-info: ${{ env.SSH_DEPLOY_KEY_INFO }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '${{ env.TF_VERSION }}'

      # A terraform init is required before a terraform taint can be run
      - name: Terraform Init
        run: terraform init

      - name: Terraform Taint
        # TODO: Add any additional parameters that are needed (-allow-missing, -lock=false, -lock-timeout=90s)
        #       https://www.terraform.io/docs/cli/commands/taint.html#usage
        run: terraform taint ${{ github.event.inputs.tf-resource-address }}

