name: Runbook - Add or update azure keyvault secret
#TODO:  You may wish to add the name of the key vault to the name above and the file name if there are multiple keyvaults this repository can add secrets to

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: The name of the secret to add, azure requires it conform to the following pattern - ^[0-9a-zA-Z-]+$
        required: true
      secret_value:
        description: The value of the secret
        required: true
      environment:
        description: The environment to add the secret to - dev|qa|stage|prod|demo|uat
        required: true
        default: prod

jobs:
  set-secret:
    runs-on: [self-hosted, ubuntu-20.04]

    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Mask the secret value
        uses: actions/github-script@v4
        with:
          script: |
            core.info(`Masking the value for ${context.payload.inputs.secret_name} so it is not exposed.`);
            core.setSecret(context.payload.inputs.secret_value);

      # TODO:  Update for the environments that are supported
      - name: Clean environment input
        id: clean-env
        uses: im-open/map-input-action@v1.0.1
        with:
          input: ${{ github.event.inputs.environment }}
          input_map: '{ "Dev": ["dev", "d", "development"], "QA": ["qa", "q"], "Stage": ["stg", "s", "stage"], "Prod": ["prod", "production", "p"], "UAT" : ["uat", "user acceptance testing", "u"], "Demo": ["demo", "o"] }'
          error_on_no_match: true
          custom_error_message: 'The environment must be Dev, QA, Stage, Demo, UAT or Prod'

      - uses: im-open/set-variable-based-on-environment@v1.0.0
        with:
          variable-name: 'KEYVAULT_NAME'
          current-environment: ${{ steps.clean-env.outputs.mapped_input}}
          dev-value: '' # TODO: Add the dev keyvault name or delete if env does not exist
          qa-value: '' # TODO: Add the qa keyvault name or delete if env does not exist
          stage-value: '' # TODO: Add the stage keyvault name or delete if env does not exist
          prod-value: '' # TODO: Add the prod keyvault name or delete if env does not exist
          demo-value: '' # TODO: Add the demo keyvault name or delete if env does not exist
          uat-value: '' # TODO: Add the uat keyvault name or delete if env does not exist

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # TODO: Ensure this secret has been populated in your repo

      - name: keyvault set
        run: az keyvault secret set --name ${{ github.event.inputs.secret_name }} --vault-name ${{ env.KEYVAULT_NAME }} --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }} --value "${{ github.event.inputs.secret_value}}"

      - name: Azure logout
        if: always() && steps.login.outcome == 'success'
        run: |
          az logout
          az cache purge
          az account clear
