# Workflow Code: distressedstoat_v5    DO NOT REMOVE
# Purpose: 
#    Pings a url and fails by default if the status code is 400+
#    
# Frequency:
#    - This workflow is intended to be used once per repository as is
#      but could be duplicated so the url-to-check can be hardcoded.
#    
# Projects to use this Template with:
#    -  On-Prem Service               (Optional Template)
#    -  Azure App Service or Function (Optional Template)


name: Runbook - Check Url
run-name: Check ${{ inputs.url-to-check }}
on:
  workflow_dispatch:
    inputs:
      url-to-check:
        description: The url to get the status of.
        required: true

jobs:
  check-status-of-url:
    steps:
      - name: Check the status code returned by the url
        uses: im-open/url-status-check@v1.1
        with:
          url: ${{ inputs.url-to-check }}
          fail-on-bad-status: true # TODO: Update this if you don't want the action to fail for 400+ response codes. Otherwise you can remove this line since the action's default is true.
