# Workflow Code: ZestyAligator_v1    DO NOT REMOVE
# Purpose:
#    Runs K6 tests at scale in Azure Kubernetes.
#    With the workflow the user specifies when they kick it off manually.
#
# Frequency:
#    - This workflow is intended to be reusable, and used once per repository.
#
# Projects to use this Template with:
#    - App Service or Function (Optional Template)
#    - On-Prem Service         (Optional Template)
# # TODO: Prerequisites:
#    - Ensure each of the repo-level MS_TEAMS_URI and env-level secrets used in this workflow have been populated by an admin in your repository.

name: Run K6 Operator Test

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to run test against [dev, qa, stage]"
        required: true
        type: choice
        options: # TODO: Update for the environments that are available
          - dev
          - qa
          - load
          - stage
          - demo
      working-directory:
        description: "Working Directory: Test folder root that contains k6 files"
        required: true
        default: './tests/k6' # TODO: Update k6 test folder path
      run-name: # Run name is used to separate load test runs from each other.
        description: "Run Name: Name of k6 test run in logs and kubernetes."
        required: true
        default: "Test-Check-Health" # TODO: Update Default k6 run name.  
      test-file:
        description: "Test Filename: K6 js test file to run. Please include .js extension"
        required: true
        default: "check-health-simple.js" # TODO: Update default test file
      upload-type:
        description: "Upload Type: Type of upload for configmap upload."
        required: true
        default: test-file # TODO: Update to default upload type
        type: choice
        options:
          - test-file
          - single-folder
          - multiple-files
          - multiple-folders
          - working-directory
      upload-files-folder:
        description: "Upload Files or Folders: Comma separated list of files or folders to include in the upload. Specify full path from working-directory root."
        required: false
        default: '' # TODO: Update to default upload file or folder
      k6-paramaters:
        description: "K6 paramaters.  This includes any tags or config files."
        required: false
        default: "--tag product=TEST,family=TEST" # TODO: Update default tags for grafana dashboard filtering.
      parallelism:
        description: "Parallelism: Number of Kubernetes Pods to run k6 tests on."
        required: false
        default: "1"
      separate-nodes:
        description: "Dedicated Node: Run each pod on individual node(VM). Warning: Coordinate with SRE before enabling."
        required: false
        type: boolean
        default: false
      run-npm-build: # TODO: Delete input if you don't build your k6 tests with npm
        description: "Run NPM Build: Run npm build to create packages k6 tests"
        required: false
        type: boolean
        default: false # TODO: Set true if you require npm build to run for your k6 bundle to be created

jobs:

  run_k6_operator:
    runs-on: [self-hosted, ubuntu-20.04]
    environment: ${{ github.event.inputs.env }}

    defaults:
      run:
        shell: bash

    env:
      TIMEZONE: 'america/denver' # TODO: Verify timezone
      GRAFANA_DASHBOARD_URI: 'https://grafana.dev.mktp.io/d/N0cdP_cnz/k6-load-testing-results?orgId=1&refresh=5s&from=now-15m&to=now' # TODO: Verify link to your dashboard
      NODE_VERSION: '16.x' # TODO: Set correct node version
      # InfluxDB addresses - Prod: http://10.206.234.29:8086/loadtesting ; Dev: http://10.206.225.188:8086/loadtesting
      # K6-Operator AKS Cluster is in the Dev Subscription, thus you have to use the Dev Influx DB
      K6_DEFAULT_PARAMATERS: '--out influxdb=http://10.206.225.188:8086/loadtesting --insecure-skip-tls-verify --tag NAME=${{ github.event.inputs.run-name }} -e RUN_ENV=${{ github.event.inputs.env-to-test }}' # TODO: Set default k6 paramaters

      ###### DO NOT EDIT ######
      CLUSTER_NAME: 'BDAIM-D-NA26-PERFTEST-K8-CL'
      CLUSTER_RESOURCE_GROUP: 'BDAIM-D-NA26-PerformanceTesting-RGRP'
      CLUSTER_DNS_ZONE_NAME: 'perftest.privatelink.westus2.azmk8s.io'
      ###### DO NOT EDIT ######

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show Input Variables
        run: |
          echo "Workflow Inputs:"
          echo "
            working-directory: ${{ github.event.inputs.working-directory }}
            test-file: ${{ github.event.inputs.test-file }}
            upload-type: ${{ github.event.inputs.upload-type }}
            upload-files-folder: '${{ github.event.inputs.upload-files-folder }}'
            k6-paramaters: '${{ github.event.inputs.k6-paramaters }}'
            k6-default-paramaters: '${{ env.K6_DEFAULT_PARAMATERS }}'
            parallelism: '${{ github.event.inputs.parallelism }}'
            separate-nodes: '${{ github.event.inputs.separate-nodes }}'
          "

      - name: Annotate Test Paramaters
        uses: actions/github-script@v6
        with:
          script: |
            var output = `
              Workflow Inputs =>
                Environment: ${{ github.event.inputs.env }};
                Test File: ${{ github.event.inputs.test-file }};
                Parallelism: ${{ github.event.inputs.parallelism }};
                Separate Nodes: ${{ github.event.inputs.separate-nodes }};
                Upload Type: ${{ github.event.inputs.upload-type }};
                Upload File/Folders: ${{ github.event.inputs.upload-files-folder}};
                K6 Paramaters: ${{ github.event.inputs.k6-paramaters }};
                K6 Default Paramaters: ${{ env.K6_DEFAULT_PARAMATERS }};
            `;
            core.notice(`${output}`);

      # TODO: Delete if you don't build your k6 tests
      - name: Install Node ${{ env.NODE_VERSION }}
        if: github.event.inputs.run-npm-build == 'true'
        uses: actions/setup-node@v2
        with:
            node-version: ${{ env.NODE_VERSION }}

      # TODO: Delete if you don't build your k6 tests
      - name: NPM Cache
        id: npm-cache
        if: github.event.inputs.run-npm-build == 'true'
        uses: actions/cache@v2
        with:
          path: '${{ github.event.inputs.working-directory }}/node_modules'
          key: ${{ runner.os }}-modules-k6-${{ hashFiles('${{ github.event.inputs.working-directory }}/package-lock.json') }}
          restore-keys: ${{ runner.os }}-modules-k6-

      # TODO: Delete if you don't build your k6 tests
      - name: Install NPM Dependencies
        if: github.event.inputs.run-npm-build == 'true' && steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
        working-directory: ${{ github.event.inputs.working-directory }}

      # TODO: Delete if you don't build your k6 tests
      - name: Build K6 Tests via npm build
        if: github.event.inputs.run-npm-build == 'true'
        run: npm run build
        working-directory: ${{ github.event.inputs.working-directory }}

      - name: Setup kubectl config
        uses: im-practices/setup-kubectl-config-for-private-aks@latest
        id: kube-config
        with:
          config-secret: ${{ secrets.K6_OPERATOR_KUBE_CONFIG }} # This is a repo-level secret (unless 'environment:' has been added to the job)
          aks-resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          aks-cluster-name: ${{ env.CLUSTER_NAME }}
          dns-zone-name: ${{ env.CLUSTER_DNS_ZONE_NAME }}
          enable-azure-login: 'true'
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Send Status to Teams - Starting Test
        continue-on-error: true
        uses: im-open/post-status-to-teams-action@v1.1.2
        with:
          title: "K6 Test Starting Shortly in AKS - ${{ github.event.inputs.run-name }}"
          workflow-status: started
          workflow-type: Runbook
          teams-uri: ${{ secrets.MS_TEAMS_URI }} # This is a repo-level secret (unless 'environment:' has been added to the job)
          timezone: ${{ env.TIMEZONE }}
          custom-facts: |
            [
              { "name": "Workflow", "value": "${{ github.workflow }}" },
              { "name": "Run", "value": "${{ github.run_id }}" },
              { "name": "Actor", "value": "${{ github.actor }}" },
              { "name": "Environment", "value": "${{ github.event.inputs.env }}"},
              { "name": "K6 Test", "value": "${{ github.event.inputs.test-file }}" }
            ]
          custom-actions: |
            [
              {
                "name": "View Grafana Dashboard",
                "uri": "${{ env.GRAFANA_DASHBOARD_URI }}"
              }
            ]

      - name: Clean Test Tag
        id: test-tag
        run: |
          k6_test_file_tag="--tag test=${{ github.event.inputs.test-file }}"
          # Removing slashes from k6_test_file_tag
          k6_test_file_tag=$(echo $k6_test_file_tag  | tr '/' '-')
          echo "::set-output name=test-tag::$k6_test_file_tag"

      - name: Run K6-Operator Test
        uses: im-practices/run-k6-operator-test@latest
        id: run-k6-operator-test
        with:
          working-directory: ./tests/k6
          test-file: ${{ github.event.inputs.test-file }}
          run-name: ${{ github.event.inputs.run-name }}
          upload-type: ${{ github.event.inputs.upload-type}}
          upload-files-folder: ${{ github.event.inputs.upload-files-folder }}
          k6-paramaters: "${{ github.event.inputs.k6-paramaters }}"
          k6-default-paramaters: "${{ env.K6_DEFAULT_PARAMATERS }} ${{ steps.test-tag.outputs.test-tag }}"
          parallelism: ${{ github.event.inputs.parallelism }}
          kube-config-file-path: ${{ steps.kube-config.outputs.kube-config-file }}

      - name: Remove kubectl config
        if: always()
        shell: bash
        continue-on-error: true
        run: |
          # Remove kubectl config
          rm -rf ${{ steps.kube-config.outputs.kube-config-file }}

      - name: Send Status to Teams - Test Finished
        if: always()
        continue-on-error: true
        uses: im-open/post-status-to-teams-action@v1.1.2
        with:
          title: "K6 Test AKS Complete - ${{ github.event.inputs.run-name }}"
          workflow-status: ${{ steps.run-k6-operator-test.outcome }}
          workflow-type: Runbook
          teams-uri: ${{ secrets.MS_TEAMS_URI }} # This is a repo-level secret (unless 'environment:' has been added to the job)
          timezone: ${{ env.TIMEZONE }}
          custom-facts: |
            [
              { "name": "Workflow", "value": "${{ github.workflow }}" },
              { "name": "Run", "value": "${{ github.run_id }}" },
              { "name": "Actor", "value": "${{ github.actor }}" },
              { "name": "Environment", "value": "${{ github.event.inputs.env }}"},
              { "name": "K6 Test", "value": "${{ github.event.inputs.test-file }}" },
              { "name": "K6 Run Name w/Timestamp", "value": "${{ steps.run-k6-operator-test.outputs.run-name }}"}
            ]
          custom-actions: |
            [
              {
                "name": "View Grafana Dashboard",
                "uri": "${{ env.GRAFANA_DASHBOARD_URI }}"
              }
            ]
