# Workflow Code: TroubledJaguar_v1    DO NOT REMOVE
# Purpose: 
#    Uses a container to run K6 with the file specified in 
#    the workflow when commits are pushed to the main branch.
#    
# Frequency:
#    - This workflow is intended to be reusable, and used once per repository.
#      If the workflow is updated to hardcode the testFile argument instead of
#      taking it in as an arg, then it could be duplicated, once per k6 project.
#    
# Projects to use this Template with:
#    - App Service or Function (Optional Template)
#    - On-Prem Service         (Optional Template)

name: K6 Automated Load Tester

on:
  push:
    branches:
      - main

env:
  testFile: '' # TODO: Add the name of the test file, like tests/k6/check-health-simple.js

jobs:
  k6_test:
    runs-on: [self-hosted, ubuntu-20.04]
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # InfluxDB addresses - Prod: http://10.206.234.29:8086/loadtesting ; Dev: http://10.206.225.188:8086/loadtesting
      - name: Run k6 test - docker
        working-directory: tests/k6 # TODO: Verify working directory of k6 tests
        run: |
          k6 run ${{ env.testFile }} --vus 1 -i 1 --insecure-skip-tls-verify -out JSON="./k6-output.json"