# Workflow Code: EnthralledOyster_v5    DO NOT REMOVE
# Purpose:
#    Checks out the repository and initiates a checkmarx scan on a schedule,
#    when someone kicks it off manually or when it is triggered by another
#    workflow, like the dotnet CI workflow.
#
# Frequency:
#    - This workflow should only be used once per repository
#
# Projects to use this Template with:
#    -  Azure App Service or Function (Core Template)
#    -  npm Package                   (Core Template)
#    -  Nuget Package                 (Core Template)
#    -  On-Prem Service               (Core Template)
#    -  On-Prem Site                  (Core Template)

name: Checkmarx CLI SAST Scan

on:
  # TODO: Verify the triggers that will be used
  workflow_dispatch:
    inputs:
      branch-tag-sha:
        description: The branch, tag or sha of the checkmarx scan should be run against.
        required: true
  schedule:
    # See the following site for help creating the right cron syntax: https://crontab.guru/
    # The cron job is specified in UTC.
    # 04:05 on Tuesday UTC
    # TODO: If keeping this trigger, change the day/time because they run our self-hosted runners
    - cron: 5 4 * * 2
  repository_dispatch:
    types: [run_checkmarx]
    # Expects a client payload like : { ref: value-of-ref}

jobs:
  scan-the-code:
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - name: Checkout main for Schedule Trigger
        uses: actions/checkout@v2
        if: github.event_name == 'schedule'

      - name: Checkout Provided Ref for Repository Dispatch Trigger
        uses: actions/checkout@v2
        if: github.event_name == 'repository_dispatch'
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Checkout provided branch/tag/sha for Workflow Dispatch Trigger
        uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.branch-tag-sha }}

      - name: Run the Scan
        id: scan
        uses: im-open/checkmarx-cli-sast-scan@v2.0.1
        with:
          checkmarx-server-url: ${{ secrets.CHECKMARX_URL }} # This is an org-level secret
          checkmarx-username: ${{ secrets.CHECKMARX_USERNAME }} # This is an org-level secret
          checkmarx-password: ${{ secrets.CHECKMARX_PASSWORD }} # This is an org-level secret
          team: 'CxServer\SP\Company\Users\BDA_IndividualMarketplace\BDAOutSourceTeamCity' # Same for all IM scans

          # TODO: Add your App name and optional project type.
          # Required Format: IndividualMarketplace.[projectName].[optional-project-type]
          # Examples: (IndividualMarketplace.1UP or IndividualMarketplace.Shopping.Mfe)
          # If you have an existing scan, view the checkmarx build step in TeamCity to find this value in the 'Checkmarx Project Name' field.
          project: 'IndividualMarketplace.'

          # TODO: Replace with any files or folders that need to be excluded from the scan.
          # Default list and format at https://github.com/im-open/checkmarx-cli-sast-scan/tree/main#excluding-files-and-folders
          # If you have an existing scan, view the checkmarx build step in TeamCity to see if there were additional exclusions added.
          # exclude-paths: ''

          # The following are default values for each available input.
          # report-name: 'CheckmarxSASTResults.pdf'
          # sast-high: 0    # This cannot exceed 0 according to our standards
          # sast-medium: 4  # This cannot exceed 4 according to our standards
          # sast-low: 11    # This cannot exceed 11 according to our standards
          # break-build: true
          # comment: '${{ github.workflow }} run #${{ github.run_number }} on branch ${{ github.ref }}.'
          # checkmarx-cli-version: 1.1.5

      - name: Upload the PDF Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Checkmarx Report
          path: ${{ steps.scan.outputs.report-path }}
