# Workflow Code: GuiltyBison_v8    DO NOT REMOVE
# Purpose:
#    Runs the Postman script specified in the workflow when someone
#    manually kicks it off or when another workflow triggers it.
#
# Frequency:
#    - This workflow can be duplicated for each Postman project in the repository
#      or it can be modified to run multiple projects.
#
# Projects to use this Template with:
#    -  App Service or Function (Optional Template)
#    -  On Prem Site            (Optional Template)
#    -  On Prem Service         (Optional Template)
#
# TODO: Prerequisites:
#    - If the project contains a local nuget.config remove it.  It interferes with restoring packages on the GitHub Action runners.
#    - Make the following npm package changes:
#      npm uninstall newman-reporter-teamcity
#    - Update the reporters an options in your package.json script.  For instance:
#      old script: "newman run tests/postman-tests/ParticipantGuidance.postman_collection.json -e tests/postman-tests/participant-guidance-prod.postman_environment.json -r cli,teamcity",
#      new script: "newman run tests/postman-tests/ParticipantGuidance.postman_collection.json -e tests/postman-tests/participant-guidance-prod.postman_environment.json -r cli,json --reporter-json-export postman-results.json",

name: Run Postman Tests

# TODO: Verify Triggers
on:
  # For manually kicking off the tests
  workflow_dispatch:
  # For programatically kicking off tests, like when a deploy finishes
  repository_dispatch:
    types: [postman]

env:
  READ_PKG_TOKEN: ${{ secrets.READ_PKG_TOKEN }} # This is an org-level secret
  PACKAGE_JSON_DIR: '' # TODO: Add the directory containing package.json
  POSTMAN_NPM_SCRIPT_NAME: '' # TODO: Add postman npm script name
  POSTMAN_RESULTS_NAME: '' # TODO: Add the name of the results file, set in npm script

jobs:
  run-postman:
    runs-on: [self-hosted, ubuntu-20.04]

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.PACKAGE_JSON_DIR }}

    steps:
      - uses: actions/checkout@v2

      # TODO: If you are using any nuget/npm packages from GitHub Packages uncomment this step
      # - name: Authenticate with GitHub Packages
      #   uses: im-open/authenticate-with-gh-package-registries@v1.0.5
      #   with:
      #     read-pkg-token: ${{ secrets.READ_PKG_TOKEN }} # This is an org-level secret
      #     orgs: 'im-client,im-enrollment,im-practices' # TODO: Verify list of orgs packages will be pulled from

      - name: Restore npm packages
        run: npm install

      - name: Run Postman Tests
        id: postman
        continue-on-error: true
        run: npm run ${{ env.POSTMAN_NPM_SCRIPT_NAME }}

      - name: Create Status check based on postman results
        id: process-postman
        uses: im-open/process-postman-test-results@v2.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          results-file: ${{ env.PACKAGE_JSON_DIR }}/${{ env.POSTMAN_RESULTS_NAME }}
          timezone: 'america/denver' # TODO: Verify timezone
          # TODO: Verify whether you want status checks, pr comments or both with the results of the tests.
          create-status-check: true
          # update-comment-if-one-exists: false # TODO: By default this creates one comment and updates it for each run.  Uncomment if you wish to have one new comment for every workflow run.
          create-pr-comment: true

      - name: Fail if postman errors
        if: steps.postman.outcome == 'failure'
        run: |
          echo "The postman tests have failures"
          exit 1
