# The purpose of this reusable job is to validate the catalog-info.yml file
# by optionally checking if the file changed in the PR, checking out the repo,
# validating the catalog-info.yml file using im-open/validate-catalog-info-file
# and optionally updating the PR comment with the validation results.

# Example Usage in a repo's workflow:
# jobs:
#  validate-catalog-info:
#    uses: im-practices/.github/.github/workflows/im-reusable-validate-catalog-info.yml@v3
#    with:
#      runs-on: im-linux
#      filename: catalog-info.yml
#      add-pr-comment: true
#      fail-validation-step-if-errors: true
#      have-validation-step-generate-job-summary: true

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The runner that this workflow will run on.'
        type: string
        required: false
        default: 'im-linux'
      filename:
        description: |
          The name of the catalog info file that contains TechHub entities.
          For most cases this will be catalog-info.yml.
        type: string
        required: false
        default: 'catalog-info.yml'
      add-pr-comment:
        description: |
          THIS ONLY APPLIES IF THE TRIGGER IS PULL_REQUEST.
          Flag indicating whether a PR comment should be made with the validation results.
          By default this is true so a PR comment will be made each time the workflow runs.
        type: boolean
        required: false
        default: true
      fail-validation-step-if-errors:
        description: Flag indicating whether the validate-catalog-info action should fail if the catalog-info.yml file contains validation errors.
        type: boolean
        required: false
        default: true
      have-validation-step-generate-job-summary:
        description: Flag indicating whether the validate-catalog-info action should add a job summary to the workflow run or not.
        type: boolean
        required: false
        default: true

jobs:
  validate-catalog-info:
    runs-on: ${{ inputs.runs-on }}
    env:
      ADD_PR_COMMENT: ${{ github.event_name == 'pull_request' && inputs.add-pr-comment == true }}

    steps:
      - name: Print inputs & variables
        uses: actions/github-script@v7
        with:
          script: |
            function printInput(inputName, inputValue, isMultilineInput){
               if (!inputValue || inputValue.trim().length === 0){
                core.info(`${inputName}: Not Provided`);
              } else if (isMultilineInput){
                console.log(`\n${inputName}:\n${inputValue}`);
              }
              else {
                core.info(`${inputName}: ${inputValue}`);
              }
            }

            core.info('Inputs');
            printInput('runs-on', '${{ inputs.runs-on }}');
            printInput('filename', '${{ inputs.filename }}');
            printInput('add-pr-comment', '${{ inputs.add-pr-comment }}');
            printInput('fail-validation-step-if-errors', '${{ inputs.fail-validation-step-if-errors }}');
            printInput('have-validation-step-generate-job-summary', '${{ inputs.have-validation-step-generate-job-summary }}');

            core.info('Context Data');
            printInput('GitHub Event', '${{ github.event_name }}');

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate ${{ inputs.filename }}
        uses: im-open/validate-catalog-info@v1
        id: validate
        with:
          filename: ${{ inputs.filename }}
          fail-if-errors: ${{ inputs.fail-validation-step-if-errors }}
          generate-job-summary: ${{ inputs.have-validation-step-generate-job-summary }}

      - name: If event is pull_request, add-pr-comment is true, and validation has failed then comment on PR with errors
        if: always() && env.ADD_PR_COMMENT == 'true' && steps.validate.outputs.is-valid != 'true'
        continue-on-error: true
        uses: im-open/update-pr-comment@v1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          comment-identifier: catalog-info-errors
          comment-content: ${{ steps.validate.outputs.errors-markdown }}
